"""add auth challenges and leased outbox delivery

Revision ID: d6de65ed565c
Revises: 111bac782bb3
Create Date: 2026-10-09 09:15:54.564857
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d6de65ed565c"
down_revision: str | Sequence[str] | None = "111bac782bb3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_challenges",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("purpose", sa.String(length=24), nullable=False),
        sa.Column("key_version", sa.String(length=32), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_email_challenges_attempts_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_challenges")),
        sa.UniqueConstraint("email", "purpose", name=op.f("uq_email_challenges_email_purpose")),
    )
    op.create_index(
        op.f("ix_email_challenges_expires_at"), "email_challenges", ["expires_at"], unique=False
    )
    op.create_table(
        "outbox_worker_controls",
        sa.Column("worker_group", sa.String(length=100), nullable=False),
        sa.Column("paused", sa.Boolean(), nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("worker_group", name=op.f("pk_outbox_worker_controls")),
    )
    op.create_table(
        "password_credentials",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_password_credentials_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_password_credentials")),
    )
    op.add_column("outbox_messages", sa.Column("claim_token", sa.UUID(), nullable=True))
    op.add_column(
        "outbox_messages", sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "outbox_messages", sa.Column("delivery_fingerprint", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "outbox_messages",
        sa.Column(
            "delivery_receipts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "outbox_messages",
        sa.Column("retry_budget", sa.Integer(), server_default=sa.text("5"), nullable=False),
    )
    op.add_column(
        "outbox_messages", sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True)
    )
    # Old auth-email workers did not create leases. Release only their unfinished
    # claims so the leased worker can retry them without resetting attempt history.
    op.execute(
        sa.text(
            """
            UPDATE outbox_messages
            SET status = 'failed',
                available_at = clock_timestamp(),
                claimed_at = NULL,
                claim_token = NULL,
                lease_expires_at = NULL,
                last_error_code = 'leased_delivery_cutover',
                updated_at = clock_timestamp()
            WHERE event_type = 'email_challenge_requested'
              AND status = 'processing'
            """
        )
    )
    op.create_index(
        op.f("ix_outbox_messages_status_lease_expires_at"),
        "outbox_messages",
        ["status", "lease_expires_at"],
        unique=False,
    )
    op.create_check_constraint(
        op.f("ck_outbox_messages_delivery_receipts_object"),
        "outbox_messages",
        "jsonb_typeof(delivery_receipts) = 'object'",
    )
    op.create_check_constraint(
        op.f("ck_outbox_messages_lease_pair_valid"),
        "outbox_messages",
        "(claim_token IS NULL AND lease_expires_at IS NULL) OR "
        "(claim_token IS NOT NULL AND lease_expires_at IS NOT NULL)",
    )
    op.create_check_constraint(
        op.f("ck_outbox_messages_retry_budget_positive"), "outbox_messages", "retry_budget > 0"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_outbox_messages_retry_budget_positive"), "outbox_messages", type_="check"
    )
    op.drop_constraint(
        op.f("ck_outbox_messages_lease_pair_valid"), "outbox_messages", type_="check"
    )
    op.drop_constraint(
        op.f("ck_outbox_messages_delivery_receipts_object"), "outbox_messages", type_="check"
    )
    op.drop_index(op.f("ix_outbox_messages_status_lease_expires_at"), table_name="outbox_messages")
    op.drop_column("outbox_messages", "deadline_at")
    op.drop_column("outbox_messages", "retry_budget")
    op.drop_column("outbox_messages", "delivery_receipts")
    op.drop_column("outbox_messages", "delivery_fingerprint")
    op.drop_column("outbox_messages", "lease_expires_at")
    op.drop_column("outbox_messages", "claim_token")
    op.drop_table("password_credentials")
    op.drop_table("outbox_worker_controls")
    op.drop_index(op.f("ix_email_challenges_expires_at"), table_name="email_challenges")
    op.drop_table("email_challenges")
    # ### end Alembic commands ###
