"""Shared application configuration, lifecycle, and value contracts."""

from ekumidayomi.core.errors import (
    ApplicationError,
    AuthenticationError,
    ConflictError,
    DependencyUnavailableError,
    ForbiddenError,
    NotFoundError,
    RateLimitError,
    ValidationError,
)
from ekumidayomi.core.settings import AppEnvironment, Settings, get_settings
from ekumidayomi.core.types import (
    CURRENCY_CODE_LENGTH,
    DEFAULT_CURRENCY,
    MONEY_PRECISION,
    MONEY_QUANTUM,
    MONEY_SCALE,
    DecimalInput,
    EntityId,
    Money,
    Page,
    PageRequest,
    new_entity_id,
    normalize_currency,
    quantize_money,
    require_utc,
    serialize_entity_id,
    serialize_utc,
    utc_now,
)

__all__ = [
    "CURRENCY_CODE_LENGTH",
    "DEFAULT_CURRENCY",
    "MONEY_PRECISION",
    "MONEY_QUANTUM",
    "MONEY_SCALE",
    "AppEnvironment",
    "ApplicationError",
    "AuthenticationError",
    "ConflictError",
    "DecimalInput",
    "DependencyUnavailableError",
    "EntityId",
    "ForbiddenError",
    "Money",
    "NotFoundError",
    "Page",
    "PageRequest",
    "RateLimitError",
    "Settings",
    "ValidationError",
    "get_settings",
    "new_entity_id",
    "normalize_currency",
    "quantize_money",
    "require_utc",
    "serialize_entity_id",
    "serialize_utc",
    "utc_now",
]
